name: Build iOS App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-15 # Update naar macOS 15 met Xcode 16+
    
    steps:
      - name: Code ophalen uit repository
        uses: actions/checkout@v4

      - name: CocoaPods installeren (indien aanwezig)
        run: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "Geen Podfile gevonden, CocoaPods stap overgeslagen."
          fi

      - name: Voer buildscript uit
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Upload Build Artifact naar GitHub
        uses: actions/upload-artifact@v4
        with:
          name: VIDIYOW-iOS-Build
          path: build/export/
          if-no-files-found: error
